### PR TITLE
Pytorch Lightning 2 compatibility

### PR DESCRIPTION
**Pull request by percevalw**
Going a bit further than #15, this PR relaxes all the upper bounds of the requirements:

- **`python`**: keep `>=3.6` (but most projects use `python>=3.7` anyway)
- `einops`: from `~=0.3.0` to `>=0.3.0`
- `tqdm`: from `~=4.56.0` to `>=4.56.0`
- `pytorch_lightning`: from `>=1.1.7,<=1.4.9` to `>=1.1.7`
- `torchmetrics`: from `==0.7.3` to `>=0.7.3`
- `rich_logger`: from `>=0.1.4` to `>=0.3.1`
- `sentencepiece`: from `~=0.1.95` to `>=0.1.95`
- `xxhash`: from `~=2.0.0` to `>=2.0.0`
- `regex`: from `~=2020.11.13` to `>=2020.11.13`
- `parse`: from `~=1.19.0` to `>=1.19.0`

and ensures that models can still be trained under `pytorch-ligthning==1.*` or `pytorch-ligthning==2.*`.

I've tested this under python 3.7, 3.8 and 3.10, with oldest & latest requirements.

Additionally, from `rich-logger>=0.3.1`, nested tqdm progress bars are rendered nicely with rich, so I added them back.

@camila-ud do you want to pull & check if this works for you ?

### CODE REVIEW

**Comment by camila-ud** [comment]
Hello @percevalw, thanks for this update! 

 I've tested the integration with medkit, and it seems to work fine.
Would it be possible to release a new version of `nlstruct` including this PR ?

**Comment by percevalw** [comment]
Yes ofc ! I was waiting for your feedback, I'll do it asap

**Comment by ghisvail** [comment]
Great to hear this is moving forward. Thank you- :pray: 

As a side note:

> python: keep >=3.6 (but most projects use python>=3.7 anyway)

Not really. Versions 3.6 and 3.7 are no longer [supported](https://devguide.python.org/versions/) and are being progressively dropped by libraries.

**Comment by ghisvail** [comment]
@camila-ud we would also need #17, similar situation as with `iamsystem` sadly.

**Comment by camila-ud** [comment]
Yes, indeed. The license should also be updated in order to be compatible with more projects.

I would be grateful if you could include the  modifications from #17 in the release.

I am just finishing the details of the operation, but I would like to integrate it soon. 
The nested entities are very useful ;)

**Comment by percevalw** [comment]
@ghisvail @camila-ud the new version 0.2.0 has just been released, thank you both for your contributions !

**Comment by ghisvail** [comment]
Awesome, thanks for addressing our issues so quickly.

**Comment by percevalw** [comment]
My pleasure ! Consider leaving a star if you end up finding it useful in your work

**Pull request merged**
